import { useState } from 'react'
import { useForm, ValidationError } from '@formspree/react'
import acadexPreview from './assets/project-previews/acadex.jpg'
import eargasmPreview from './assets/project-previews/eargasm.jpg'
import fleetPreview from './assets/project-previews/fleet.jpg'
import leakPreview from './assets/project-previews/leak.jpg'
import smartBuyPreview from './assets/project-previews/smart-buy.jpg'
import stridePreview from './assets/project-previews/stride.jpg'

const projects = [
  { title: 'CLINICKA', year: '2026', category: 'Full-stack web system', description: 'A secure clinic information and records workspace for Brokenshire College.', stack: 'React · NestJS · MySQL', link: 'https://github.com/B0GARTT00/CLINICKA', cover: 'Clinicka', featured: true },
  { title: 'LeakDetection', year: '2025', category: 'Mobile product', description: 'A field-ready reporting app for Davao City Water District, designed around clear utility workflows.', stack: 'React Native · Mobile UI', link: 'https://github.com/abllenos/LeakDetectionV1', image: leakPreview },
  { title: 'Fleettrack', year: '2025', category: 'Web application', description: 'A fleet management dashboard built around data, operations, and useful admin workflows.', stack: 'Laravel · PHP', link: 'https://github.com/B0GARTT00/fleettrack', image: fleetPreview },
  { title: 'Smart Buy', year: '2024', category: 'Mobile product', description: 'A grocery companion that brings budgeting and list-making into one considered flow.', stack: 'React Native · MobX', link: 'https://github.com/B0GARTT00/Smart-Buy', image: smartBuyPreview },
  { title: 'AcadexV4', year: '2025', category: 'Capstone platform', description: 'A collaborative academic platform created with classmates at Brokenshire College.', stack: 'Laravel · Team project', link: 'https://github.com/B0GARTT00/ACADEXV4', image: acadexPreview },
  { title: 'Eargasm', year: '2024', category: 'Mobile concept', description: 'An audio-focused app exploration with an emphasis on simple, fluid mobile navigation.', stack: 'React Native · JavaScript', link: 'https://github.com/B0GARTT00/Eargasm', image: eargasmPreview },
  { title: 'Stride Quest', year: '2024', category: 'Fitness app', description: 'A fitness app with progress tracking, workout flows, achievements, and profile views.', stack: 'Mobile UI · Product flows', link: 'https://github.com/B0GARTT00/StrideQuest-V2', image: stridePreview },
]
const skills = ['React', 'React Native', 'TypeScript', 'Laravel', 'PHP', 'MySQL', 'Firebase', 'UI implementation']
const caseStudies = [
  { title: 'CLINICKA', number: '01', cover: 'Clinicka', problem: 'School clinic teams need one secure place to manage patient records, visits, appointments, documents, and day-to-day workflows.', role: 'Full-stack developer', contribution: 'Built the foundation for a secure clinic management system: React workflows, a NestJS REST API, MySQL with Prisma, and role-based access.', outcomes: ['Patient records and electronic health-record workflows', 'JWT authentication, role-based access, and audit events', 'Appointments, inventory, documents, and clearances'], link: 'https://github.com/B0GARTT00/CLINICKA' },
  { title: 'LeakDetection', number: '02', image: leakPreview, problem: 'Field reporting needs to be quick and understandable when the work is happening outside the office.', role: 'Mobile developer', contribution: 'Designed and built mobile-first reporting screens around the practical needs of a utility workflow.', outcomes: ['Clear reporting flow for field use', 'Mobile-first interface decisions', 'Practical screens connected to product logic'], link: 'https://github.com/abllenos/LeakDetectionV1' },
  { title: 'Fleettrack', number: '03', image: fleetPreview, problem: 'Fleet information is only useful when it can be read, managed, and acted on without friction.', role: 'Full-stack developer', contribution: 'Built a dashboard-style web application with data-centered screens and admin-oriented workflows.', outcomes: ['Dashboard interface for operations', 'Laravel and PHP application foundation', 'Structured data and management flows'], link: 'https://github.com/B0GARTT00/fleettrack' },
]
function Arrow() { return <span aria-hidden="true">↗</span> }

function App() {
  const [state, handleSubmit] = useForm('xykvwwpw')
  const [openStudy, setOpenStudy] = useState('CLINICKA')
  const featured = projects.find((project) => project.featured)!
  return <main>
    <nav className="topbar" aria-label="Main navigation"><a className="wordmark" href="#top">KYLE LAMIGO<span>.</span></a><div className="nav-links"><a href="#work">Work</a><a href="#about">About</a><a href="#contact">Contact</a></div></nav>
    <section className="hero" id="top"><p className="eyebrow">Independent developer · Philippines</p><h1>I make digital<br /><em>products</em> feel considered.</h1><div className="hero-bottom"><p>I’m Kyle — a full-stack developer focused on clear interfaces, practical product thinking, and web and mobile experiences that work beautifully.</p><a className="text-link" href="#work">Selected work <Arrow /></a></div></section>
    <section className="work-section" id="work"><div className="section-heading"><p className="eyebrow">01 / Selected work</p><p className="muted">A growing collection of web and mobile products, made with attention to the details people actually use.</p></div>
      <a className="featured-work" href={featured.link} target="_blank" rel="noreferrer"><div className={`featured-image ${featured.cover ? 'product-cover' : ''}`}>{featured.cover ? <span>{featured.cover}</span> : <img src={featured.image} alt={`${featured.title} app preview`} />}</div><div className="featured-copy"><div><span>{featured.category}</span><span>{featured.year}</span></div><h2>{featured.title} <Arrow /></h2><p>{featured.description}</p><small>{featured.stack}</small></div></a>
      <div className="project-grid">{projects.filter((project) => !project.featured).map((project) => <a className="project" href={project.link} target="_blank" rel="noreferrer" key={project.title}><div className="project-image"><img src={project.image} alt={`${project.title} preview`} loading="lazy" /></div><div className="project-meta"><span>{project.category}</span><span>{project.year}</span></div><h3>{project.title} <Arrow /></h3><p>{project.description}</p><small>{project.stack}</small></a>)}</div>
      <div className="case-study-section"><div className="case-study-heading"><p className="eyebrow">A closer look</p><h2>Project stories</h2></div>{caseStudies.map((study) => <article className={`case-study ${openStudy === study.title ? 'open' : ''}`} key={study.title}><button className="case-study-trigger" type="button" onClick={() => setOpenStudy(openStudy === study.title ? '' : study.title)} aria-expanded={openStudy === study.title}><span>{study.number}</span><strong>{study.title}</strong><span>{openStudy === study.title ? '−' : '+'}</span></button>{openStudy === study.title && <div className="case-study-body">{study.cover ? <div className="case-cover">{study.cover}</div> : <img src={study.image} alt={`${study.title} project preview`} />}<div><p className="case-label">The brief</p><p>{study.problem}</p><p className="case-label">My contribution</p><p>{study.contribution}</p><div className="case-meta"><span>Role</span><strong>{study.role}</strong></div><ul>{study.outcomes.map((outcome) => <li key={outcome}>{outcome}</li>)}</ul><a className="case-link" href={study.link} target="_blank" rel="noreferrer">View repository <Arrow /></a></div></div>}</article>)}</div>
    </section>
    <section className="about-section" id="about"><p className="eyebrow">02 / About</p><div className="about-grid"><h2>Useful, elegant,<br />and built to last.</h2><div><p className="about-intro">I enjoy turning an idea into something people can navigate without thinking twice. My work sits between thoughtful interface design and the engineering that makes it reliable.</p><p className="muted">I’m especially drawn to frontend, full-stack, and mobile development roles where I can keep learning, contribute to a good team, and ship work that has a real purpose.</p><div className="skill-list" aria-label="Core skills">{skills.map((skill) => <span key={skill}>{skill}</span>)}</div></div></div></section>
    <section className="contact-section" id="contact"><p className="eyebrow">03 / Contact</p><div className="contact-grid"><div><h2>Have something<br /><em>in mind?</em></h2><p className="muted">I’m open to frontend, full-stack, and mobile opportunities. Let’s talk about what you’re building.</p><div className="socials"><a href="https://github.com/B0GARTT00" target="_blank" rel="noreferrer">GitHub <Arrow /></a><a href="https://www.facebook.com/kyle.lamigo.18" target="_blank" rel="noreferrer">Facebook <Arrow /></a></div></div>
      {state.succeeded ? <div className="success-message"><p className="eyebrow">Message sent</p><h3>Thank you.</h3><p>I’ll get back to you as soon as I can.</p></div> : <form onSubmit={handleSubmit}><label>Name<input name="name" required placeholder="Your name" /></label><label>Email<input name="email" type="email" required placeholder="you@example.com" /></label><ValidationError field="email" errors={state.errors} className="form-error" /><label>Message<textarea name="message" required placeholder="Tell me a little about the opportunity" /></label><ValidationError field="message" errors={state.errors} className="form-error" /><button type="submit" disabled={state.submitting}>{state.submitting ? 'Sending…' : <>Send a message <Arrow /></>}</button></form>}</div></section>
    <footer><span>© 2026 Kyle Lamigo</span><span>Designed and developed with care</span></footer>
  </main>
}
export default App
